### ISSUE TITLE
Narrative system

### ISSUE THREAD

**Issue by MattBlack343** [UoSGamesGroups/first-semester-l4-5-group-6#20]
I'd like you to program the narrative system that we've discussed previously.

**Comment by moccy** [comment]
Made it so that you can add your narrative to a text file. The Dialog Box system will read the text file and split it up in to lines. You can then specify which lines will be read, and then each line will be output to the dialog box. You can go to the next line by pressing the 'E' key. In the future I want to make it so that the text scrolls on character by character instead of line by line, and so that the text importing method is more flexible and scalable.
